name: tmiv-advanced-ml-platform
channels:
  - conda-forge
dependencies:
  # --- Python + kluczowe binarne zależności z conda (szybkie, stabilne) ---
  - python=3.11
  - pip
  - numpy>=1.26
  - pandas>=2.2
  - scipy>=1.11
  - scikit-learn>=1.4
  - matplotlib>=3.8
  - pillow>=10
  - pyarrow>=16         # szybkie IO Parquet/Arrow w pandas
  - openpyxl>=3.1       # XLSX import
  - streamlit>=1.36
  - reportlab>=4.0      # PDF export
  - diskcache>=5.6
  - shap>=0.45          # (opcjonalnie) Explainability
  - lightgbm            # (opcjonalnie) jeśli chcesz LGBM
  - xgboost             # (opcjonalnie) jeśli chcesz XGBoost
  # - catboost          # zwykle wygodniej przez pip; możesz dopisać tu, jeśli wolisz

  # --- Reszta przez pip (definiowana w requirements.txt) ---
  - pip:
      - -r requirements.txt
