name: hackathon-ml-project
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11

  # Core Data Science Stack
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy==1.15.1
  - scikit-learn>=1.3.0
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0

  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0

  # Web Framework
  - streamlit>=1.28.0

  # Database
  - sqlalchemy>=2.0.0
  - psycopg2>=2.9.0

  # Advanced ML
  - xgboost>=1.7.0
  - lightgbm>=3.3.0

  # Performance
  - numba>=0.57.0

  # Development Tools
  - black>=23.0.0
  - flake8>=6.0.0
  - statsforecast==2.0.2
  - pytest>=7.4.0
  - mypy>=1.5.0

  # File Processing
  - openpyxl>=3.1.0
  - xlrd>=2.0.0

  # Utilities
  - tqdm>=4.65.0
  - python-dateutil>=2.8.0

  # Configuration
  - python-dotenv>=1.0.0
  
  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - openai>=0.27.0
    - anthropic>=0.3.0
    - memory-profiler>=0.61.0
    - cryptography>=41.0.0