name: tmiv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.0
  - pip:
      - streamlit>=1.37.0
      - pandas>=2.2.0
      - numpy>=1.26.0
      - scikit-learn>=1.5.0
      - xgboost>=2.0.0
      - lightgbm>=4.1.0
      - catboost>=1.2.0
      - plotly>=5.18.0
      - matplotlib>=3.8.0
      - seaborn>=0.13.0
      - ydata-profiling>=4.6.0
      - reportlab>=4.0.0
      - pydantic>=2.5.0
      - pydantic-settings>=2.1.0
      - python-dotenv>=1.0.0
      - joblib>=1.3.0
      - openpyxl>=3.1.0
      - pyarrow>=14.0.0
      - cryptography>=41.0.0
      - openai>=1.0.0
      - anthropic>=0.18.0
      - pytest>=7.4.0
      - pytest-asyncio>=0.21.0
      - pytest-cov>=4.1.0
      - ruff>=0.1.0
      - black>=23.12.0
      - isort>=5.13.0
      - mypy>=1.7.0
      - types-requests>=2.31.0
      - pandas-stubs>=2.1.0