[project]
name = "tmiv-advanced-ml-platform"
version = "2.0.0"
description = "The Most Important Variables – Advanced ML Platform v2.0 Pro (skeleton)"
readme = "docs/README.md"
requires-python = ">=3.11"
