version: 1

formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
  json:
    format: |
      {"ts":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","msg":"%(message)s","module":"%(module)s","lineno":%(lineno)d}

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
  console_json:
    class: logging.StreamHandler
    formatter: json
    level: INFO
  file_rotating:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    level: INFO
    filename: logs/app.log
    maxBytes: 10485760   # 10 MB
    backupCount: 3
    encoding: utf-8

loggers:
  app:                    # nasz logger aplikacyjny
    handlers: [console]
    level: INFO
    propagate: False
  backend:                # np. backend.*
    handlers: [console]
    level: INFO
    propagate: False
  matplotlib:
    handlers: [console]
    level: WARNING
    propagate: False

root:
  level: INFO
  handlers: [console]
