name: CI

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff isort pytest mypy pre-commit

      - name: Pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Lint
        run: |
          black --check .
          ruff check .
          isort --check-only .

      - name: Type check
        run: mypy .

      - name: Tests
        run: pytest -q

      - name: Pack repo artifact
        run: |
          zip -r tmiv-advanced-ml-platform-${{ github.sha }}.zip . -x ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tmiv-advanced-ml-platform-${{ github.sha }}
          path: tmiv-advanced-ml-platform-${{ github.sha }}.zip
