name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint & Test (skeleton)
        run: |
          python -m pip install black ruff isort pytest
          black --check .
          ruff check .
          isort --check-only .
          pytest -q
