name: TMIV CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Parquet/XLSX engines
        pip install pyarrow openpyxl

    - name: Lint
      run: |
        python -m pip install ruff black mypy
        ruff check . || true
        black --check . || true
        mypy --ignore-missing-imports . || true

    - name: Tests
      run: |
        pytest -q

    - name: Upload artifacts (if present)
      uses: actions/upload-artifact@v4
      with:
        name: tmiv-artifacts-${{ matrix.os }}
        path: |
          artifacts/reports/*.pdf
          artifacts/exports/*.zip
        if-no-files-found: ignore