
name: CI
on:
  push:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        py: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff mypy black
      - name: Lint
        run: ruff check .
      - name: Type-check
        run: mypy backend ml || true
      - name: Tests
        run: pytest -q
