name: Release Zip
on:
  push:
    tags:
      - 'v*'
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip
        run: |
          zip -r tmiv-advanced-ml-platform.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tmiv-advanced-ml-platform
          path: tmiv-advanced-ml-platform.zip
