# .streamlit/config.toml
[theme]
base = "dark"
primaryColor = "#8A2BE2"
backgroundColor = "#0E0F13"
secondaryBackgroundColor = "#16181D"
textColor = "#EAEAF2"
font = "sans serif"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
headless = false
enableCORS = true              # <-- nie wyłączaj przy włączonym XSRF
enableXsrfProtection = true
address = "localhost"          # <-- zamiast "0.0.0.0" dla auto-open lokalnie
port = 8501

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
magicEnabled = false
fastReruns = true

[logger]
level = "info"
